# Generated by Django 5.0.4 on 2024-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='intentos',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
