# Generated by Django 5.0.4 on 2024-05-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesiones', '0002_persona_intentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='dni',
            field=models.IntegerField(),
        ),
    ]
