# Generated by Django 5.0.4 on 2024-05-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.TextField(default='disponible'),
            preserve_default=False,
        ),
    ]
