# Generated by Django 5.0.4 on 2024-05-01 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sesiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellido', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('dni', models.BigIntegerField()),
                ('usuarioId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sesiones.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion_din',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pago', models.TextField()),
                ('monto', models.FloatField()),
                ('donacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.donacion')),
            ],
        ),
        migrations.CreateModel(
            name='Donacion_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('donacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.donacion')),
            ],
        ),
    ]
