# Generated by Django 5.0.4 on 2024-05-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0003_alter_publicacion_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='aceptada',
        ),
        migrations.AddField(
            model_name='publicacion',
            name='estado',
            field=models.TextField(default='disponible'),
            preserve_default=False,
        ),
    ]
