# Generated by Django 5.0.6 on 2024-05-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofrecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofrecimiento',
            name='imagen',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
