# Generated by Django 5.0.4 on 2024-05-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofrecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofrecimiento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
