# Generated by Django 5.0.6 on 2024-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofrecimientos', '0002_alter_ofrecimiento_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofrecimiento',
            name='estado',
            field=models.TextField(default='pendiente'),
            preserve_default=False,
        ),
    ]
