# Generated by Django 5.0.6 on 2024-06-20 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercambios', '0001_initial'),
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='IntercambioHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiales.historial')),
                ('intercambioId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercambios.intercambio')),
            ],
        ),
        migrations.CreateModel(
            name='PublicacionHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historiales.historial')),
                ('publicacionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publicaciones.publicacion')),
            ],
        ),
    ]
