# Generated by Django 5.0.4 on 2024-05-01 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ofrecimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intercambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.TextField()),
                ('ofrecimientoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofrecimientos.ofrecimiento')),
            ],
        ),
    ]
