# Generated by Django 5.0.4 on 2024-05-03 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intercambios', '0001_initial'),
        ('ofrecimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intercambio',
            name='ofrecimientoId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ofrecimientos.ofrecimiento'),
        ),
    ]
